# Re-export everything that was importable from the old scripts/webapp_backend.py module.
# Tests import from scripts.webapp_backend — nothing must break.

from ai_enquiry_ranker import merge_ai_rankings, rank_matches_with_ai  # noqa: F401
from enquiry_matcher import clean_number, match_enquiry  # noqa: F401

from .ai_engine import (  # noqa: F401
    ai_client_report_prompt,
    ai_fallback_prompt,
    ai_feedback_prompt,
    ai_scenario_prompt,
    ai_scenario_rank_prompt,
    ai_scenario_report_prompt,
    ai_scenario_result,
    check_openai_key,
)
from .constants import (  # noqa: F401
    AI_DESCRIPTION_CHARS,
    COMMUNITY_ALIASES,
    CONDITION_FEATURES,
    DEFAULT_AI_BATCH_SIZE,
    DEFAULT_AI_FINAL_CANDIDATE_LIMIT,
    DEFAULT_AI_RESULT_LIMIT,
    DEFAULT_AI_SHORTLIST_LIMIT,
    DEFAULT_RENT_STRETCH_RATIO,
    DEFAULT_RESULT_LIMIT,
    DEFAULT_SALE_STRETCH_RATIO,
    MARKET_COMMUNITIES,
    MARKET_CONTEXT_TRANSACTION_LIMIT,
    MARKET_RENTALS_FILE,
    MARKET_RENTALS_PREDICTED_FILE,
    MARKET_SALES_FILE,
    MARKET_SALES_PREDICTED_FILE,
    MONTH_ALIASES,
    MUST_HAVE_TERMS,
    OVER_BUDGET_LIMIT,
    OWNER_LEADS_FILE,
    RENT_BUDGET_FLOOR_RATIO,
    RENT_OVER_BUDGET_RATIO,
    SALE_BUDGET_FLOOR_RATIO,
    SALE_OVER_BUDGET_RATIO,
    SCENARIOS,
    SIMILAR_MARKET_GROUPS,
    VILLA_COMMUNITIES,
    VILLA_TYPE_REFERENCE_FILE,
)
from .data_loader import (  # noqa: F401
    clean_market_number,
    load_market_rentals,
    load_market_sales,
    read_master,
)
from .estimator import (  # noqa: F401
    load_villa_type_reference,
    lookup_type_reference,
    parse_condition_features,
    parse_villa_type_from_text,
    valuation_estimate,
)
from .opportunity_scanner import opportunity_scan  # noqa: F401
from .market_context import (  # noqa: F401
    active_match_communities,
    active_shortlist_market_summary,
    build_market_context,
    build_rental_market_context,
    compact_market_row,
    compact_rental_market_row,
    filter_master_by_listing_scope,
    listing_scope_communities,
    market_context_communities,
    numeric_summary,
    similar_market_communities_for,
)
from .matcher import (  # noqa: F401
    build_budget_fallback_dataframe,
    build_budget_reality_primary_dataframe,
    build_matches_dataframe,
    build_over_budget_dataframe,
    fallback_compromise_ceiling,
    match_prompt,
    metric_html,
    money,
    normalize_quick_text,
    over_budget_ceiling,
    premium_fallback_band,
    premium_townhouse_score,
    quick_category_mask,
    quick_int,
    quick_listing_query,
    quick_money,
)
from .owner_lookup import (  # noqa: F401
    clean_value,
    extract_urls,
    find_column,
    lookup_owner,
    lookup_owner_in_df,
    normalize_url,
    owner_payload_from_row,
    owner_property_summary,
    owner_row_value,
)
from .prompt_parser import (  # noqa: F401
    default_budget_floor,
    default_stretch_budget,
    has_strict_budget_language,
    infer_purpose,
    normalize_market_communities,
    normalize_market_scope,
    normalize_search_intent,
    parse_bedroom_options,
    parse_budget_from_prompt,
    parse_budget_reality_mode,
    parse_communities_from_text,
    parse_community,
    parse_explicit_category,
    parse_move_month,
    parse_must_haves,
    parse_preferred_category,
    parse_preferred_villa_types,
    parse_prompt,
    parse_stretch_budget_from_prompt,
)
from .result_builder import (  # noqa: F401
    add_similar_listing_warnings,
    duplicate_text_tokens,
    has_exclusive_warning,
    likely_duplicate_group_key,
    result_payload,
    rows_payload,
)
